### PR TITLE
This pull request resolves #192, resolves #197, and resolves #207

### LINKED ISSUE #192: (styles) resize congrats! page so that there's no scrolling, and score / level text overlays the canvas, and get rid of canvas background

### LINKED ISSUE #197: welcomeboard needs to re-render on screen resize

### LINKED ISSUE #207: (bug) After 5th challenge is completed, site freezes

### PR DESCRIPTION
**Pull request by ndharithreesan**
- canvas resizes and the board is redrawn on window resize
- congrats page is styled
- arrow is clickable again
- board resets every 5 levels

### CODE REVIEW

**Comment by mwbennett** [comment]
:+1: :cool:

**Comment by DaveDH2** [comment]
:+1:

**Comment by mwbennett** [comment]
:+1:

**Comment by LaurenSpiegel** [comment]
:+1:

**Pull request merged**
