### PR TITLE
This pull request resolves #16

### LINKED ISSUE #16: Create contributing guide

### PR DESCRIPTION
**Pull request by ndharithreesan**
This change will add documentation regarding contribution guidelines. It also updates the project README.md to include the team information and a link to the contributing file.

### CODE REVIEW

**Comment by mwbennett** [comment]
:+1: lookin solid. great first pull request for our shiny new repo!

**Comment by LaurenSpiegel** [comment]
This looks beautiful!  My only suggested change is I would add Nimi and me as development team members as well.

**Comment by DaveDH2** [comment]
+1 CodeRevelRepeat's comment, looks good.

**Comment by ndharithreesan** [comment]
The changes have been committed! Please re-review

**Comment by mwbennett** [comment]
:+1: nice, nice

**Comment by LaurenSpiegel** [comment]
All good!

**Comment by DaveDH2** [comment]
+1 nice =D

**Pull request merged**
