### PR TITLE
This pull request resolves #128, resolves #129

### LINKED ISSUE #128: add timeout to worker

### LINKED ISSUE #129: is a user fails a challenge, the error doesnt show up on the instructions

### PR DESCRIPTION
**Pull request by ndharithreesan**
This adds a timeout to the webworker and fixes the issue of the failure messages not showing up in the instructions component

### CODE REVIEW

**Comment by mwbennett** [comment]
:+1: awesome work

**Comment by LaurenSpiegel** [comment]
:+1: :+1:

**Comment by DaveDH2** [comment]
:+1:

**Comment by mwbennett** [comment]
Lauren trying to one-up everyone with her double-thumbs :stuck_out_tongue_winking_eye:

**Comment by LaurenSpiegel** [comment]
:+1:  :+1:  :+1:

**Pull request merged**
