### PR TITLE
This pull request resolves #97

### LINKED ISSUE #97: logo is not visible when user is logged in
Placeholder text appears instead

### PR DESCRIPTION
**Pull request by mwbennett**
- Returns logo to header regardless of whether or not user is logged in 
- Fixes country input styling on the signup form 
- Initial attempt to style chat component

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
:+1:

**Comment by DaveDH2** [comment]
:+1:

**Comment by ndharithreesan** [comment]
:+1: looking fly homefry

**Comment by DaveDH2** [comment]
:hushed: :+1:

**Pull request merged**
