### PR TITLE
This pull request resolves #159, resolves #195

### LINKED ISSUE #159: organize challenges

### LINKED ISSUE #195: (styles) create visual separation between the task to be performed in the challenge and the general description / story

### PR DESCRIPTION
**Pull request by DaveDH2**
-Update server.js with those 15 tests
-Add tests for those 15 challenges

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
:+1:  You have force true in server.js to reset the database each time.

**Comment by ndharithreesan** [comment]
:+1:

**Comment by ndharithreesan** [comment]
:+1:

**Comment by mwbennett** [comment]
:+1:

**Pull request merged**
