### PR TITLE
This pull request resolves #96 and resolves #62.

### LINKED ISSUE #62: check authentication should send token to back end to be decoded and checked

### LINKED ISSUE #96: (bug) user is disappearing on refresh

### PR DESCRIPTION
**Pull request by LaurenSpiegel**
-Fix authorization and routing.

### CODE REVIEW

**Comment by DaveDH2** [comment]
:+1:

**Comment by DaveDH2** [comment]
:+1:

**Comment by mwbennett** [comment]
:+1: this is awesome :dog:

**Comment by ndharithreesan** [comment]
:+1: this is great and I have no hate

**Pull request merged**
