### PR TITLE
This pull request resolves #146.

### LINKED ISSUE #146: update girl with computer login picture

### PR DESCRIPTION
**Pull request by LaurenSpiegel**
-Updates picture of girl (less purple).
-Re-styles button on login page leading to signup page.

### CODE REVIEW

**Comment by mwbennett** [comment]
do we need to crop the new one the same way we cropped the old one?

**Comment by DaveDH2** [comment]
:+1:

**Comment by ndharithreesan** [comment]
:+1:

**Comment by LaurenSpiegel** [comment]
No need to crop.  The alignment works.

**Comment by mwbennett** [comment]
:+1: :100:

**Pull request merged**
