### PR TITLE
This pull request resolves #66

### LINKED ISSUE #66: Refactor frontend routing

### PR DESCRIPTION
**Pull request by mwbennett**
Refactor frontend routing. Deleted all views in favor of directly rendering components. Need to add one more redirect in Challenge Store for all view routing to be correct.

### CODE REVIEW

**Comment by DaveDH2** [comment]
:100:  :+1:

**Comment by LaurenSpiegel** [comment]
Great stuff!

1) In main.js, should we make the default route Login?

2) In components/challengeEditor.js line 56, do we need to state this.state.value?

**Comment by mwbennett** [comment]
@CodeRevelRepeat: what happens when a logged-in user tries to navigate to login. Will it automatically redirect them to home?

**Comment by ndharithreesan** [comment]
:+1:

**Pull request merged**
