### PR TITLE
This pull request resolves #73

### LINKED ISSUE #73: increment user's score and level on completion of a challenge

### PR DESCRIPTION
**Pull request by mwbennett**
- When a user completes a challenge, their score and level are updated and saved to the database. 
- New route /api/users/:name added for updating score and level attributes. 
- Added a second challenge (hard-coded in server.js) and test file for testing challenges with different pointValues 
- Updated welcome and congrats views to reflect the correct user level

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
Looks great!  I love how you distinguish between "welcome" and "welcome back".  Nice touch.  Why are we showing the user's level as the level minus one?

**Comment by mwbennett** [comment]
The user data gets updated as soon as the challenge is completed, so the user's current challenge is 1 greater than the challenge we are congratulating them on completing when the "congrats" view displays, if that makes sense.

**Comment by ndharithreesan** [comment]
:+1:

**Comment by LaurenSpiegel** [comment]
Makes sense.  Thanks!  :+1:

**Comment by DaveDH2** [comment]
:+1:

**Pull request merged**
